name: Test Secret

# on
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.TEST_SECRET}}
    
    steps:
      - uses: actions/checkout@v2
      - run: echo $TEST_SECRET
