name: Automatically Deployment

on: [push]

env:
  key: nothing

jobs:
  deployment:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write  
  
    runs-on: ubuntu-latest

    name: Deploying to GitHub Pages

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Assign value into .env
        run: echo "This is my old env object value, ${{ env.key }}"

      - name: Print .env
        env: 
          key: ${{ secrets.TEST_SECRET }}      
        run: echo "This is my new env object value, ${{ env.key }}"

      # - name: Generate Environment Variables File for Production
      #  run: |
      #    echo "TEST_SECRET=$TEST_SECRET" >> .env.production
      #  env:
      #    TEST_SECRET: ${{ secrets.TEST_SECRET }}

      - name: Install Dependencies
        run: |
          npm install

      - name: Build React Application
        run: npm run build
       
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "/static/js/main"
          replace: "static/js/main"
          include: "build/index.html"
          
      - name: Deploy React Application to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          
